/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface IpSlider {
    'disabled': boolean;
    'max': number;
    'min': number;
    'step': number;
    'value': number;
  }
  interface IpSliderAttributes extends StencilHTMLAttributes {
    'disabled'?: boolean;
    'max'?: number;
    'min'?: number;
    'onInput'?: (event: CustomEvent) => void;
    'step'?: number;
    'value'?: number;
  }
}

declare global {
  interface StencilElementInterfaces {
    'IpSlider': Components.IpSlider;
  }

  interface StencilIntrinsicElements {
    'ip-slider': Components.IpSliderAttributes;
  }


  interface HTMLIpSliderElement extends Components.IpSlider, HTMLStencilElement {}
  var HTMLIpSliderElement: {
    prototype: HTMLIpSliderElement;
    new (): HTMLIpSliderElement;
  };

  interface HTMLElementTagNameMap {
    'ip-slider': HTMLIpSliderElement
  }

  interface ElementTagNameMap {
    'ip-slider': HTMLIpSliderElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
